quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ppmp
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.username=ppmp-bot
quarkus.datasource.password=secret
quarkus.smallrye-openapi.info-title=PPMP
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.store-schema-directory=target/openapi
quarkus.smallrye-openapi.store-schema-file-name=openapi
quarkus.smallrye-openapi.store-schema-format=yaml
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with